### ISSUE TITLE
TS typing error with generic factory function for generic model instance

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#405]
I've discovered another typing issue related to generic models when using a generic factory function to create a new model instance. This is a test case that reproduces the problem:

```ts
test("generic model instance factory", () => {
  // @model("Parent")
  class Parent<T> extends Model(<T>() => ({
    a: prop<T>(),
  }))<T> {}

  // @model("Child")
  class Child<T> extends ExtendedModel(<T>() => ({
    baseModel: modelClass<Parent<T>>(Parent),
    props: {
      b: prop<T>(),
    },
  }))<T> {}

  // @ts-ignore
  // eslint-disable-next-line
  function createParent<T>(a: T) {
    const parent = new Parent({ a })
    assert(_ as typeof parent, _ as Parent<T>) // ERROR
  }

  // @ts-ignore
  // eslint-disable-next-line
  function createChild<T>(a: T, b: T) {
    const child = new Child({ a, b })
    assert(_ as typeof child, _ as Child<T>) // ERROR
  }
})
```

I've tried to fix it but have not been successful so far.

**Comment by xaviergonz** [comment]
Fixed in this commit https://github.com/xaviergonz/mobx-keystone/commit/8f8d22b95829b3363320d12e2262d13a56474985

**Comment by xaviergonz** [comment]
v0.66.1

**Comment by sisp** [comment]
Awesome! :tada: Thank you very much for the prompt fix!

**Comment by sisp** [comment]
I'm afraid it's not fully resolved. When you add an ID prop, a typing error occurs again:

```diff
test("generic model instance factory", () => {
   @model("generic model instance factory/Parent")
   class Parent<T> extends Model(<T>() => ({
+    id: idProp,
     a: prop<T>(),
   }))<T> {}
```

**Comment by sisp** [comment]
Actually, it's not about the ID prop, but the problem is related to any optional prop, e.g.:

```diff
test("generic model instance factory", () => {
   @model("generic model instance factory/Parent")
   class Parent<T> extends Model(<T>() => ({
+    x: prop<number | undefined>(),
     a: prop<T>(),
   }))<T> {}
```

**Comment by xaviergonz** [comment]
I think T being there is messing up the detection of optional properties, but as a workaround if you pass `x: undefined` explicitly it works

**Comment by sisp** [comment]
Hm, yes, but I can't pass `undefined` for `id`. :thinking:

**Comment by sisp** [comment]
I think I found a fix - see #407.

**Comment by sisp** [comment]
Do you happen to know why, e.g.,

```ts
assert(_ as Flatten<ModelCreationData<Parent<string>>>, _ as { a: string; x?: number })
```

works fine but

```ts
assert(_ as Flatten<ModelCreationData<typeof parent>>, _ as { a: T; x?: number })
```

(inside [`function createParent<T>(a: T>) { ... }`](https://github.com/xaviergonz/mobx-keystone/blob/da4e046170f585831ae26a7932de51e3571ea20a/packages/lib/test/model/subclassing.test.ts#L796)) doesn't?

**Comment by xaviergonz** [comment]
My guess is that the typing system doesn't know what to make of T. Is it really optional or is it not? T could be string | undefined and then it would be optional. or it could not if it doesn't include undefined

**Comment by sisp** [comment]
Good point, sounds reasonable. Thanks! :slightly_smiling_face:
